const fontawesome = require("@fortawesome/fontawesome");
const faGithub = require("@fortawesome/fontawesome-free-brands/faGithub");
const faCogs = require("@fortawesome/fontawesome-free-solid/facogs");
const faEdit = require("@fortawesome/fontawesome-free-regular/faedit");
const faMap=require("@fortawesome/fontawesome-free-regular/faMap");
const faFacebook = require("@fortawesome/fontawesome-free-brands/faFacebook");
const faTwitter = require("@fortawesome/fontawesome-free-brands/faTwitter");
const faYoutube = require("@fortawesome/fontawesome-free-brands/faYoutube");
const faInstagram= require("@fortawesome/fontawesome-free-brands/faInstagram");
fontawesome.library.add(faInstagram, faYoutube, faTwitter, faFacebook,faMap);